const data = {
  lastUpdatedOn: '2020-08-28T11:46:10.832Z',
  players: [
    {
      player: {
        id: 19003,
        firstName: 'DeMarkus',
        lastName: 'Acy',
        primaryPosition: 'CB',
        alternatePositions: [],
        jerseyNumber: null,
        currentTeam: {
          id: 78,
          abbreviation: 'SF',
        },
        currentRosterStatus: 'ROSTER',
        currentInjury: null,
        height: '6\'2"',
        weight: 195,
        birthDate: '1998-04-29',
        age: 22,
        birthCity: null,
        birthCountry: 'USA',
        rookie: false,
        highSchool: null,
        college: 'Missouri',
        handedness: null,
        officialImageSrc: null,
        socialMediaAccounts: [],
        currentContractYear: null,
        drafted: null,
        externalMappings: [],
      },
      teamAsOfDate: {
        id: 78,
        abbreviation: 'SF',
      },
    },
    {
      player: {
        id: 19004,
        firstName: 'Salvon',
        lastName: 'Ahmed',
        primaryPosition: 'RB',
        alternatePositions: [],
        jerseyNumber: null,
        currentTeam: {
          id: 78,
          abbreviation: 'SF',
        },
        currentRosterStatus: 'ROSTER',
        currentInjury: null,
        height: '5\'11"',
        weight: 196,
        birthDate: '1998-12-29',
        age: 21,
        birthCity: null,
        birthCountry: 'USA',
        rookie: false,
        highSchool: 'Juanita',
        college: 'Washington',
        handedness: null,
        officialImageSrc: null,
        socialMediaAccounts: [],
        currentContractYear: null,
        drafted: null,
        externalMappings: [],
      },
      teamAsOfDate: {
        id: 78,
        abbreviation: 'SF',
      },
    },
    {
      player: {
        id: 18675,
        firstName: 'Brandon',
        lastName: 'Aiyuk',
        primaryPosition: 'WR',
        alternatePositions: [],
        jerseyNumber: null,
        currentTeam: {
          id: 78,
          abbreviation: 'SF',
        },
        currentRosterStatus: 'ROSTER',
        currentInjury: null,
        height: '6\'0"',
        weight: 201,
        birthDate: '1998-03-17',
        age: 22,
        birthCity: null,
        birthCountry: 'USA',
        rookie: false,
        highSchool: 'Robert McQueen',
        college: 'Arizona State',
        handedness: null,
        officialImageSrc: null,
        socialMediaAccounts: [],
        currentContractYear: null,
        drafted: null,
        externalMappings: [],
      },
      teamAsOfDate: {
        id: 78,
        abbreviation: 'SF',
      },
    },
    {
      player: {
        id: 16135,
        firstName: 'Azeez',
        lastName: 'Al-Shaair',
        primaryPosition: 'LB',
        alternatePositions: [],
        jerseyNumber: 51,
        currentTeam: {
          id: 78,
          abbreviation: 'SF',
        },
        currentRosterStatus: 'ROSTER',
        currentInjury: null,
        height: '6\'2"',
        weight: 228,
        birthDate: '1997-08-04',
        age: 23,
        birthCity: null,
        birthCountry: null,
        rookie: false,
        highSchool: null,
        college: 'Florida Atlantic',
        handedness: null,
        officialImageSrc:
          'http://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/ALS107778.png',
        socialMediaAccounts: [],
        currentContractYear: null,
        drafted: null,
        externalMappings: [
          {
            source: 'NFL.com Stats Leaders',
            id: 'ALS107778',
          },
        ],
      },
      teamAsOfDate: {
        id: 78,
        abbreviation: 'SF',
      },
    },
    {
      player: {
        id: 8605,
        firstName: 'Kwon',
        lastName: 'Alexander',
        primaryPosition: 'MLB',
        alternatePositions: [],
        jerseyNumber: 56,
        currentTeam: {
          id: 78,
          abbreviation: 'SF',
        },
        currentRosterStatus: 'ROSTER',
        currentInjury: null,
        height: '6\'1"',
        weight: 227,
        birthDate: '1994-08-03',
        age: 26,
        birthCity: 'Oxford, AL',
        birthCountry: 'USA',
        rookie: false,
        highSchool: null,
        college: 'LSU',
        handedness: null,
        officialImageSrc:
          'http://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/ALE492854.png',
        socialMediaAccounts: [],
        currentContractYear: null,
        drafted: {
          year: 2015,
          team: {
            id: 71,
            abbreviation: 'TB',
          },
          pickTeam: {
            id: 71,
            abbreviation: 'TB',
          },
          round: 4,
          roundPick: 28,
          overallPick: 124,
        },
        externalMappings: [
          {
            source: 'NFL.com Stats Leaders',
            id: 'ALE492854',
          },
        ],
      },
      teamAsOfDate: {
        id: 78,
        abbreviation: 'SF',
      },
    },
    {
      player: {
        id: 16478,
        firstName: 'Joey',
        lastName: 'Alfieri',
        primaryPosition: 'LB',
        alternatePositions: [],
        jerseyNumber: 50,
        currentTeam: {
          id: 78,
          abbreviation: 'SF',
        },
        currentRosterStatus: 'ROSTER',
        currentInjury: null,
        height: '6\'2"',
        weight: 226,
        birthDate: '1996-03-06',
        age: 24,
        birthCity: null,
        birthCountry: null,
        rookie: false,
        highSchool: null,
        college: 'Stanford',
        handedness: null,
        officialImageSrc:
          'http://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/ALF046143.png',
        socialMediaAccounts: [],
        currentContractYear: null,
        drafted: null,
        externalMappings: [
          {
            source: 'NFL.com Stats Leaders',
            id: 'ALF046143',
          },
        ],
      },
      teamAsOfDate: {
        id: 78,
        abbreviation: 'SF',
      },
    },
    {
      player: {
        id: 12964,
        firstName: 'Kofi',
        lastName: 'Amichia',
        primaryPosition: 'G',
        alternatePositions: [],
        jerseyNumber: 79,
        currentTeam: {
          id: 78,
          abbreviation: 'SF',
        },
        currentRosterStatus: 'ROSTER',
        currentInjury: null,
        height: '6\'3"',
        weight: 305,
        birthDate: '1994-07-29',
        age: 26,
        birthCity: 'East Point, GA',
        birthCountry: 'USA',
        rookie: false,
        highSchool: null,
        college: 'South Florida',
        handedness: null,
        officialImageSrc:
          'http://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/AMI118653.png',
        socialMediaAccounts: [],
        currentContractYear: null,
        drafted: {
          year: 2017,
          team: {
            id: 62,
            abbreviation: 'GB',
          },
          pickTeam: {
            id: 62,
            abbreviation: 'GB',
          },
          round: 6,
          roundPick: 52,
          overallPick: 212,
        },
        externalMappings: [
          {
            source: 'NFL.com Stats Leaders',
            id: 'AMI118653',
          },
        ],
      },
      teamAsOfDate: {
        id: 78,
        abbreviation: 'SF',
      },
    },
    {
      player: {
        id: 8420,
        firstName: 'Arik',
        lastName: 'Armstead',
        primaryPosition: 'DE',
        alternatePositions: [],
        jerseyNumber: 91,
        currentTeam: {
          id: 78,
          abbreviation: 'SF',
        },
        currentRosterStatus: 'ROSTER',
        currentInjury: null,
        height: '6\'7"',
        weight: 290,
        birthDate: '1993-11-15',
        age: 26,
        birthCity: 'Sacramento, CA',
        birthCountry: 'USA',
        rookie: false,
        highSchool: null,
        college: 'Oregon',
        handedness: null,
        officialImageSrc:
          'http://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/ARM057964.png',
        socialMediaAccounts: [],
        currentContractYear: null,
        drafted: {
          year: 2015,
          team: {
            id: 78,
            abbreviation: 'SF',
          },
          pickTeam: {
            id: 78,
            abbreviation: 'SF',
          },
          round: 1,
          roundPick: 17,
          overallPick: 17,
        },
        externalMappings: [
          {
            source: 'NFL.com Stats Leaders',
            id: 'ARM057964',
          },
        ],
      },
      teamAsOfDate: {
        id: 78,
        abbreviation: 'SF',
      },
    },
    {
      player: {
        id: 12938,
        firstName: 'Alex',
        lastName: 'Barrett',
        primaryPosition: 'DE',
        alternatePositions: [],
        jerseyNumber: 79,
        currentTeam: {
          id: 78,
          abbreviation: 'SF',
        },
        currentRosterStatus: 'ROSTER',
        currentInjury: null,
        height: '6\'3"',
        weight: 260,
        birthDate: '1994-03-06',
        age: 26,
        birthCity: 'Yuma, AZ',
        birthCountry: 'USA',
        rookie: false,
        highSchool: null,
        college: null,
        handedness: null,
        officialImageSrc: null,
        socialMediaAccounts: [],
        currentContractYear: null,
        drafted: null,
        externalMappings: [],
      },
      teamAsOfDate: {
        id: 78,
        abbreviation: 'SF',
      },
    },
    {
      player: {
        id: 13469,
        firstName: 'C.J.',
        lastName: 'Beathard',
        primaryPosition: 'QB',
        alternatePositions: [],
        jerseyNumber: 3,
        currentTeam: {
          id: 78,
          abbreviation: 'SF',
        },
        currentRosterStatus: 'ROSTER',
        currentInjury: null,
        height: '6\'2"',
        weight: 215,
        birthDate: '1993-11-16',
        age: 26,
        birthCity: 'Nashville, TN',
        birthCountry: 'USA',
        rookie: false,
        highSchool: 'Battle Ground Academy',
        college: 'Iowa',
        handedness: {
          throws: null,
        },
        officialImageSrc:
          'http://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/BEA000000.png',
        socialMediaAccounts: [],
        currentContractYear: null,
        drafted: {
          year: 2017,
          team: {
            id: 78,
            abbreviation: 'SF',
          },
          pickTeam: {
            id: 78,
            abbreviation: 'SF',
          },
          round: 3,
          roundPick: 40,
          overallPick: 104,
        },
        externalMappings: [
          {
            source: 'NFL.com Stats Leaders',
            id: 'BEA000000',
          },
        ],
      },
      teamAsOfDate: {
        id: 78,
        abbreviation: 'SF',
      },
    },
  ],
  references: {
    teamReferences: [
      {
        id: 78,
        city: 'San Francisco',
        name: '49ers',
        abbreviation: 'SF',
        homeVenue: {
          id: 68,
          name: "Levi's Stadium",
        },
        teamColoursHex: ['#aa0000', '#b3995d'],
        socialMediaAccounts: [
          {
            mediaType: 'TWITTER',
            value: '49ers',
          },
        ],
        officialLogoImageSrc:
          'https://static.www.nfl.com/image/private/t_q-best/league/dxibuyxbk0b9ua5ih9hn',
      },
    ],
    venueReferences: [
      {
        id: 68,
        name: "Levi's Stadium",
        city: 'Santa Clara, CA',
        country: 'USA',
        geoCoordinates: {
          latitude: 37.403,
          longitude: -121.97,
        },
        capacitiesByEventType: [
          {
            eventType: 'FOOTBALL',
            capacity: 75000,
          },
        ],
        playingSurface: 'Tifway II Bermuda Grass',
        baseballDimensions: [],
        hasRoof: false,
        hasRetractableRoof: false,
      },
    ],
  },
};

export default data;
